runtime: nodejs16

instance_class: F2

service: release-candidate

env_variables:
  BUCKET_NAME: 'dmhub-webhub'

handlers:
  - url: /
    static_files: rc/dist/web-hub/index.html
    upload: rc/dist/web-hub/index.html

  - url: /
    static_dir: rc/dist/web-hub
