runtime: nodejs16

instance_class: F2

service: release-candidate

env_variables:
  BUCKET_NAME: 'dmhub-webhub-rc'

handlers:
  - url: /
    static_files: dist/web-hub/index.html
    upload: dist/web-hub/index.html

  - url: /
    static_dir: dist/web-hub
