runtime: nodejs16

instance_class: F2

service: development

env_variables:
  BUCKET_NAME: 'dmhub-webhub'

handlers:
  - url: /
    static_files: dev/dist/web-hub/index.html
    upload: dev/dist/web-hub/index.html

  - url: /
    static_dir: dev/dist/web-hub
