on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Verify contents
        run: ls -la
        
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Verify contents
        run: ls -la
        
      - name: Upload files
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'dist'
          destination: 'dmhub-webhub'
          parent: false          
          
     # - name: Move files to App Engine
     #   run: gsutil rsync -d -r gs://dmhub-webhub ./webhub-gcp

      - name: Deploy
        run: gcloud app deploy app.yaml
